### ISSUE TITLE
添加 payer的时候报错： 请确保该值小于等于2147483647

### ISSUE THREAD

**Issue by liziqiang0523** [heqiqi/aws_partner_billing_system#1]
<img width="492" alt="image" src="https://github.com/heqiqi/aws_partner_billing_system/assets/13741799/1cba1755-7cca-455a-8905-c747914ebbd4">

**Comment by heqiqi** [comment]
测试了下，是可以添加这么长的account Id的。
![image](https://github.com/heqiqi/aws_partner_billing_system/assets/3094813/eeceb5b9-053b-4cc7-9ddf-783972de3d87)
