### ISSUE TITLE
每个link账号中都要创建一个S3吗

### ISSUE THREAD

**Issue by GGSeven** [heqiqi/aws_partner_billing_system#5]
文档步骤：设置Stackset,在每个Linked的账户内开启Cost Usage Report，并将parque格式的CUR保存在link账号S3 Bucket内

**Comment by heqiqi** [comment]
使用stackset可以自动创建s3的。

GGSeven ***@***.***> 于 2023年12月29日周五 16:34写道：

**Comment by GGSeven** [comment]
我的意思是这个s3会创建在link账号里面 这不是相当于每个link账号要加一笔这个s3的费用支出吗

**Comment by heqiqi** [comment]
是会有费用的。但是，和集中创建在payer里的费用一样的。
并且link里的cur更灵活。

GGSeven ***@***.***> 于 2023年12月30日周六 00:00写道：

**Comment by GGSeven** [comment]
感谢开发者的回复   还有就是我在调用lambda/cpy_linked_s3_to_payer.py时候  IAM没有权限调用link账号的s3存储桶内容 lambda执行结果提示：An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
IAM是按照教程中进行权限设置的

**Comment by heqiqi** [comment]
看下你payer下lambda执行role是否和s3 bucket policy一致。

GGSeven ***@***.***> 于 2023年12月30日周六 00:03写道：

**Comment by GGSeven** [comment]
刚刚查看了一下 我link账号S3的存储桶策略没有内容 
![image](https://github.com/heqiqi/aws_partner_billing_system/assets/66481676/23e42bb6-4898-4fd0-be00-c29e0bd481a9)

**Comment by GGSeven** [comment]
这是我的lambda执行role
![image](https://github.com/heqiqi/aws_partner_billing_system/assets/66481676/44ed5c3f-7aaa-428b-83ae-9a25d1cad2a1)
![image](https://github.com/heqiqi/aws_partner_billing_system/assets/66481676/802a0e79-90ef-4f43-b762-619a28809d89)

**Comment by heqiqi** [comment]
那是stackset没有执行

GGSeven ***@***.***> 于 2023年12月30日周六 00:09写道：

**Comment by GGSeven** [comment]
lambda/cpy_linked_s3_to_payer.py函数设置Stackset后权限问题解决了 现在出现无法找到对应的S3  lambda函数是在payer账号中执行  但是通过Stackset创建的S3在linked账号中  然后执行调用出现   not existed  的报错 这个是什么问题呢 
![image](https://github.com/heqiqi/aws_partner_billing_system/assets/66481676/aa3b6a51-6f18-4b75-89c8-13633adf28c7)
我在函数中添加了打印 print(LINKED_CUR_PREFIX+acc)  print(OBJECT_KEY+acc) 发现这两个S3不存在于payer账号中 linked账号中只有s3  organization-enable-cur-890xxxxx
